image: alpine:latest

stages:
  - test
  - run

secret-detection:
  stage: test
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --source . --no-git --verbose --redact

code-quality:
  stage: test
  image: node:16.13
  only:
    - merge_requests
  script:
    - npm install
    - npm run build
    - npm run lint

run:
  image: node:16.13
  when: manual
  only:
    refs:
      - main
  before_script:
    - apt-get update
    - apt-get install -yq gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
  script:
    - npm install
    - npm run build
    - npm run once
  artifacts:
    when: always
    paths:
      - results/*

run-trigger:
  image: node:16.13
  except:
    variables:
      - $EXTERNAL != "true"
  only:
    refs:
      - main
  before_script:
    - apt-get update
    - apt-get install -yq gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
  script:
    - npm install
    - npm run build
    - npm run once
  after_script:
    - npm run post-results
  artifacts:
    when: always
    paths:
      - results/*
